services:
  database:
    container_name: postgres
    image: postgres:15.2
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:5.0
    restart: always
    ports:
      - 6379:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - backend
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:

networks:
  backend:
